apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-poller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-poller
subjects:
  - kind: ServiceAccount
    name: github-poller
    namespace: default

